#!/usr/bin/env python3
"""
generate_passages_json.py – Generate data/key_passages.json
with all curated Bible passages organised across 18 themes.

Usage:  python3 tools/generate_passages_json.py
Run from the repository root.
"""
import json
import os
import pathlib

REPO_ROOT = pathlib.Path(__file__).parent.parent
OUTPUT = REPO_ROOT / "data" / "key_passages.json"

# ── Data ──────────────────────────────────────────────────────────────────
# Each passage: (title, book_id, ch_from, v_from, ch_to, v_to)
# Book IDs follow the Elberfelder 1905 CSV column "Book Number".

THEMES = [
    (1, "Schöpfung und Ursprung", "🌍", [
        ("Die Erschaffung der Welt",          1,  1,  1,  2,  4),
        ("Das Paradies",                       1,  2,  4,  2, 25),
        ("Der Sündenfall",                     1,  3,  1,  3, 24),
        ("Kain und Abel",                      1,  4,  1,  4, 16),
        ("Die Sintflut und Noahs Bund",        1,  6,  5,  9, 17),
    ]),
    (2, "Die Erzväter und Mütter Israels", "👨‍👩‍👧‍👦", [
        ("Gottes Bund mit Abraham",            1, 12,  1, 12,  9),
        ("Gott verheißt Abraham einen Sohn",   1, 15,  1, 15,  6),
        ("Hagar und Ismael",                   1, 16,  1, 16, 16),
        ("Der Bund mit der Beschneidung",      1, 17,  1, 17, 27),
        ("Abrahams Fürbitte für Sodom",        1, 18, 16, 18, 33),
        ("Sodom und Gomorra",                  1, 19,  1, 19, 29),
        ("Die Geburt Isaaks",                  1, 21,  1, 21,  7),
        ("Die Opferung Isaaks",                1, 22,  1, 22, 19),
        ("Die Brautwerbung für Isaak",         1, 24,  1, 24, 67),
        ("Esau und Jakob",                     1, 25, 19, 25, 34),
        ("Isaak segnet Jakob",                 1, 27,  1, 27, 40),
        ("Jakobs Himmelsleiter",               1, 28, 10, 28, 22),
        ("Jakob bei Laban und seine Familie",  1, 29,  1, 30, 43),
        ("Jakobs Kampf am Jabbok",             1, 32, 23, 32, 33),
        ("Jakobs Versöhnung mit Esau",         1, 33,  1, 33, 20),
        ("Josefs Träume",                      1, 37,  1, 37, 11),
        ("Josef wird nach Ägypten verkauft",   1, 37, 12, 37, 36),
        ("Josef und die Frau Potifars",        1, 39,  1, 39, 23),
        ("Josef deutet die Träume des Pharao", 1, 41,  1, 41, 40),
        ("Josefs Versöhnung mit seinen Brüdern", 1, 45, 1, 45, 28),
    ]),
    (3, "Der Auszug aus Ägypten und die Wüstenzeit", "⛏️", [
        ("Moses Geburt und Berufung",                    2,  2,  1,  4, 17),
        ("Die zehn Plagen",                              2,  7, 14, 12, 30),
        ("Das Passa und der Auszug",                     2, 12,  1, 12, 42),
        ("Der Durchzug durchs Schilfmeer",               2, 14,  1, 14, 31),
        ("Das Manna in der Wüste",                       2, 16,  1, 16, 36),
        ("Wasser aus dem Felsen",                        2, 17,  1, 17,  7),
        ("Die Schlacht gegen Amalek",                    2, 17,  8, 17, 16),
        ("Die Offenbarung am Sinai und die Zehn Gebote", 2, 19,  1, 20, 21),
        ("Das Bundesbuch",                               2, 20, 22, 23, 33),
        ("Der Bund am Sinai",                            2, 24,  1, 24, 18),
        ("Die Stiftshütte",                              2, 25,  1, 31, 18),
        ("Das Goldene Kalb",                             2, 32,  1, 32, 35),
        ("Der Aaronsche Segen",                          4,  6, 22,  6, 27),
        ("Die Kundschafter in Kanaan",                   4, 13,  1, 14, 45),
        ("Mose darf das Land nicht betreten",            5, 34,  1, 34, 12),
    ]),
    (4, "Gesetz und Bund", "📜", [
        ("Das Hauptgebot",     5,  6,  4,  6,  9),
        ("Das Erlassjahr",     5, 15,  1, 15, 11),
        ("Das Sozialgesetz",   5, 24, 10, 24, 22),
        ("Segen und Fluch",    5, 28,  1, 28, 68),
        ("Der neue Bund",     24, 31, 31, 31, 34),
    ]),
    (5, "Einzug und Landnahme", "⚔️", [
        ("Die Berufung Josuas",             6,  1,  1,  1,  9),
        ("Der Durchzug durch den Jordan",   6,  3,  1,  4, 24),
        ("Die Eroberung von Jericho",       6,  6,  1,  6, 27),
        ("Der Bundesschluss in Sichem",     6, 24,  1, 24, 28),
        ("Debora und Barak",                7,  4,  1,  5, 31),
    ]),
    (6, "Die Zeit der Richter", "⚖️", [
        ("Die Berufung Gideons",                                  7,  6,  1,  6, 40),
        ("Simsons Geburt und Berufung",                           7, 13,  1, 13, 25),
        ("Simson und Delila",                                     7, 16,  1, 16, 31),
        ("Rut und Noomi",                                         8,  1,  1,  4, 22),
        ("Jeder tat, was recht war in seinen Augen",              7, 17,  6, 17,  6),
    ]),
    (7, "Könige und Prophetie in Israel", "👑", [
        ("Die Geburt Samuels",                     9,  1,  1,  1, 28),
        ("Die Berufung Samuels",                   9,  3,  1,  3, 21),
        ("Die Forderung nach einem König",         9,  8,  1,  8, 22),
        ("Die Salbung Sauls",                      9,  9,  1, 10, 27),
        ("Davids Salbung",                         9, 16,  1, 16, 13),
        ("David und Goliath",                      9, 17,  1, 17, 58),
        ("Davids Freundschaft mit Jonathan",       9, 18,  1, 18,  4),
        ("David schont Saul",                      9, 24,  1, 24, 22),
        ("Davids Buße nach dem Ehebruch",         10, 12,  1, 12, 25),
        ("Absaloms Aufstand und Tod",             10, 18,  1, 18, 33),
        ("Salomos Bitte um Weisheit",             11,  3,  1,  3, 15),
        ("Das Urteil Salomos",                    11,  3, 16,  3, 28),
        ("Der Tempelbau",                         11,  6,  1,  6, 38),
        ("Die Königin von Saba",                  11, 10,  1, 10, 13),
        ("Die Reichsteilung",                     11, 12,  1, 12, 33),
    ]),
    (8, "Die großen Propheten Elia und Elisa", "🔥", [
        ("Elia am Bach Krit und bei der Witwe",   11, 17,  1, 17, 24),
        ("Das Gottesurteil auf dem Karmel",       11, 18, 20, 18, 46),
        ("Elia am Gottesberg Horeb",              11, 19,  1, 19, 18),
        ("Der Weinberg Nabots",                   11, 21,  1, 21, 29),
        ("Elias Himmelfahrt",                     12,  2,  1,  2, 18),
        ("Elisa und die Witwe",                   12,  4,  1,  4,  7),
        ("Elisa und die Sunamitin",               12,  4,  8,  4, 37),
        ("Die Heilung Naamans",                   12,  5,  1,  5, 27),
        ("Jona flieht vor Gott",                  32,  1,  1,  1, 17),
        ("Jona in Ninive",                        32,  3,  1,  3, 10),
    ]),
    (9, "Psalmen: Gebete und Lieder", "🎵", [
        ("Herr, mein Gott (Psalm 13)",                 19, 13,  1, 13,  6),
        ("Der Herr ist mein Licht (Psalm 27)",         19, 27,  1, 27, 14),
        ("Gott, sei mir gnädig (Psalm 51)",            19, 51,  1, 51, 21),
        ("Wie der Hirsch lechzt (Psalm 42)",           19, 42,  1, 42, 12),
        ("Gott ist unsre Zuversicht (Psalm 46)",       19, 46,  1, 46, 12),
        ("Der gute Hirte (Psalm 23)",                  19, 23,  1, 23,  6),
        ("Gott, mein Schöpfer (Psalm 8)",              19,  8,  1,  8, 10),
        ("Der Mensch im Lichte Gottes (Psalm 90)",     19, 90,  1, 90, 17),
        ("Lobet den Herrn, meine Seele (Psalm 103)",   19,103,  1,103, 22),
        ("Du erforschest mich (Psalm 139)",            19,139,  1,139, 24),
        ("Dank für Gottes Güte (Psalm 92)",            19, 92,  1, 92, 16),
        ("Jauchzt dem Herrn, alle Lande! (Psalm 100)", 19,100,  1,100,  5),
        ("Der Herr sprach zu meinem Herrn (Psalm 110)",19,110,  1,110,  7),
        ("Halleluja (Psalm 117)",                      19,117,  1,117,  2),
        ("Freude über das Gesetz (Psalm 119)",         19,119,  1,119,176),
        ("Wo Hilfe herkommt (Psalm 121)",              19,121,  1,121,  8),
        ("Wohl dem, der den Herrn fürchtet (Psalm 128)",19,128, 1,128,  8),
        ("Tief aus der Tiefe (Psalm 130)",             19,130,  1,130,  8),
        ("Lobe den Herrn, meine Seele (Psalm 146)",    19,146,  1,146, 10),
        ("Das Lied der Hanna",                          9,  2,  1,  2, 10),
        ("Das Danklied des Jona",                      32,  2,  2,  2, 10),
        ("Der Lobgesang Marias – Magnificat",          42,  1, 46,  1, 55),
        ("Der Lobgesang des Zacharias – Benedictus",   42,  1, 68,  1, 79),
        ("Der Lobgesang des Simeon – Nunc dimittis",   42,  2, 29,  2, 32),
    ]),
    (10, "Prophetische Bücher und Botschaft", "📣", [
        ("Die Berufung Jesajas",          23,  6,  1,  6, 13),
        ("Das Weinberglied",              23,  5,  1,  5,  7),
        ("Das Zeichen Immanuels",         23,  7, 10,  7, 17),
        ("Ein Kind ist uns geboren",      23,  9,  1,  9,  6),
        ("Der Friede im Friedensreich",   23, 11,  1, 11, 10),
        ("Trost für Gottes Volk",         23, 40,  1, 40, 31),
        ("Der Gottesknecht",              23, 52, 13, 53, 12),
        ("Die Berufung Jeremias",         24,  1,  4,  1, 10),
        ("Der Ton beim Töpfer",           24, 18,  1, 18, 12),
        ("Jeremias Tempelrede",           24,  7,  1,  7, 34),
        ("Die Vision vom Totenfeld",      26, 37,  1, 37, 14),
        ("Das Gastmahl des Belsazar",     27,  5,  1,  5, 31),
        ("Daniel in der Löwengrube",      27,  6,  1,  6, 29),
        ("Schwerter zu Pflugscharen",     33,  4,  1,  4,  5),
        ("Was der Herr von dir fordert",  33,  6,  8,  6,  8),
    ]),
    (11, "Jesus Christus: Geburt und Kindheit", "⭐", [
        ("Der Stammbaum Jesu",                              40,  1,  1,  1, 17),
        ("Die Weisen aus dem Morgenland",                   40,  2,  1,  2, 12),
        ("Die Flucht nach Ägypten",                         40,  2, 13,  2, 23),
        ("Die Ankündigung der Geburt Jesu",                 42,  1, 26,  1, 38),
        ("Marias Besuch bei Elisabeth",                     42,  1, 39,  1, 45),
        ("Der Lobgesang Marias",                            42,  1, 46,  1, 55),
        ("Die Geburt Johannes des Täufers",                 42,  1, 57,  1, 80),
        ("Die Geburt Jesu in Bethlehem",                    42,  2,  1,  2, 20),
        ("Die Beschneidung und Darstellung im Tempel",      42,  2, 21,  2, 40),
        ("Der zwölfjährige Jesus im Tempel",                42,  2, 41,  2, 52),
    ]),
    (12, "Jesu Wirken: Taufe, Versuchung und Berufung", "🕊️", [
        ("Johannes der Täufer",              40,  3,  1,  3, 12),
        ("Die Taufe Jesu",                   40,  3, 13,  3, 17),
        ("Die Versuchung Jesu",              40,  4,  1,  4, 11),
        ("Die Berufung der ersten Jünger",   40,  4, 18,  4, 22),
        ("Die Berufung des Matthäus",        40,  9,  9,  9, 13),
        ("Die Aussendung der Zwölf",         40, 10,  1, 10, 42),
        ("Die Hochzeit zu Kana",             43,  2,  1,  2, 12),
        ("Die Samariterin am Brunnen",       43,  4,  1,  4, 42),
        ("Jesus in Nazareth",                42,  4, 16,  4, 30),
        ("Der Hauptmann von Kapernaum",      40,  8,  5,  8, 13),
    ]),
    (13, "Die Bergpredigt", "⛰️", [
        ("Die Seligpreisungen",                       40,  5,  1,  5, 12),
        ("Salz und Licht",                            40,  5, 13,  5, 16),
        ("Jesus und das Gesetz",                      40,  5, 17,  5, 20),
        ("Von Ehe und Scheidung",                     40,  5, 27,  5, 32),
        ("Von der Feindesliebe",                      40,  5, 38,  5, 48),
        ("Vom Almosengeben und Beten",                40,  6,  1,  6, 18),
        ("Das Vaterunser",                            40,  6,  9,  6, 13),
        ("Von Schätzen im Himmel und Sorgen",         40,  6, 19,  6, 34),
        ("Vom Richten",                               40,  7,  1,  7,  6),
        ("Die Goldene Regel und der Hausbau",         40,  7, 12,  7, 27),
    ]),
    (14, "Gleichnisse Jesu", "🌱", [
        ("Vom Sämann",                                   40, 13,  1, 13, 23),
        ("Vom Unkraut unter dem Weizen",                 40, 13, 24, 13, 43),
        ("Vom Senfkorn und Sauerteig",                   40, 13, 31, 13, 33),
        ("Vom Schatz im Acker und von der Perle",        40, 13, 44, 13, 46),
        ("Von den Arbeitern im Weinberg",                40, 20,  1, 20, 16),
        ("Vom barmherzigen König",                       40, 18, 23, 18, 35),
        ("Von den klugen und törichten Jungfrauen",      40, 25,  1, 25, 13),
        ("Von den anvertrauten Talenten",                40, 25, 14, 25, 30),
        ("Vom Weltgericht",                              40, 25, 31, 25, 46),
        ("Vom Weinberg",                                 40, 21, 33, 21, 46),
        ("Vom barmherzigen Samariter",                   42, 10, 25, 10, 37),
        ("Vom reichen Kornbauer",                        42, 12, 13, 12, 21),
        ("Vom verlorenen Schaf und verlorenen Groschen", 42, 15,  1, 15, 10),
        ("Vom verlorenen Sohn",                          42, 15, 11, 15, 32),
        ("Vom ungerechten Verwalter",                    42, 16,  1, 16, 13),
        ("Vom reichen Mann und armen Lazarus",           42, 16, 19, 16, 31),
        ("Vom Pharisäer und Zöllner",                    42, 18,  9, 18, 14),
        ("Vom großen Abendmahl",                         42, 14, 15, 14, 24),
        ("Vom Feigenbaum",                               42, 13,  6, 13,  9),
    ]),
    (15, "Wunder und Heilungen", "✨", [
        ("Die Stillung des Sturms",                                41,  4, 35,  4, 41),
        ("Die Heilung eines Gelähmten",                           41,  2,  1,  2, 12),
        ("Die Speisung der Fünftausend",                          40, 14, 13, 14, 21),
        ("Jesus geht auf dem Wasser",                             40, 14, 22, 14, 33),
        ("Die Heilung der blutflüssigen Frau und der Tochter Jairus", 41, 5, 21, 5, 43),
        ("Die Heilung des Blindgeborenen",                        43,  9,  1,  9, 41),
        ("Die Auferweckung des Lazarus",                          43, 11,  1, 11, 45),
        ("Die Heilung des besessenen Geraseners",                 41,  5,  1,  5, 20),
        ("Die Heilung des Knechtes des Hauptmanns",               40,  8,  5,  8, 13),
        ("Die Heilung der gekrümmten Frau",                       42, 13, 10, 13, 17),
    ]),
    (16, "Passion und Auferstehung Jesu", "✝️", [
        ("Der Einzug in Jerusalem",               40, 21,  1, 21, 11),
        ("Die Tempelreinigung",                   40, 21, 12, 21, 17),
        ("Das Letzte Abendmahl",                  40, 26, 17, 26, 30),
        ("Die Fußwaschung",                       43, 13,  1, 13, 20),
        ("Jesus in Gethsemane",                   40, 26, 36, 26, 46),
        ("Die Gefangennahme und Verleugnung",     40, 26, 47, 26, 75),
        ("Jesus vor Pilatus und Herodes",         42, 23,  1, 23, 25),
        ("Die Kreuzigung und der Tod Jesu",       42, 23, 26, 23, 49),
        ("Die Grablegung Jesu",                   40, 27, 57, 27, 66),
        ("Das leere Grab",                        43, 20,  1, 20, 10),
        ("Die Erscheinung vor Maria Magdalena",   43, 20, 11, 20, 18),
        ("Der Gang nach Emmaus",                  42, 24, 13, 24, 35),
        ("Die Erscheinung vor Thomas",            43, 20, 24, 20, 29),
        ("Der Missionsbefehl",                    40, 28, 16, 28, 20),
        ("Die Himmelfahrt",                       44,  1,  6,  1, 11),
    ]),
    (17, "Die Apostelgeschichte und die Briefe", "📬", [
        ("Die Ausgießung des Heiligen Geistes (Pfingsten)", 44,  2,  1,  2, 41),
        ("Die erste Gemeinde in Jerusalem",                44,  2, 42,  2, 47),
        ("Die Heilung des Lahmen",                         44,  3,  1,  3, 26),
        ("Die Steinigung des Stephanus",                   44,  7, 54,  7, 60),
        ("Die Bekehrung des Saulus",                       44,  9,  1,  9, 19),
        ("Die Areopagrede des Paulus",                     44, 17, 16, 17, 34),
        ("Rechtfertigung aus Glauben",                     45,  3, 21,  3, 31),
        ("Abrahams Glaube",                                45,  4,  1,  4, 25),
        ("Friede mit Gott",                                45,  5,  1,  5, 11),
        ("Der neue Mensch in Christus",                    45,  6,  1,  6, 11),
        ("Das Leben im Geist",                             45,  8,  1,  8, 17),
        ("Das Hohelied der Liebe",                         46, 13,  1, 13, 13),
        ("Die Auferstehung der Toten",                     46, 15,  1, 15, 58),
        ("Die Früchte des Geistes",                        48,  5, 16,  5, 26),
        ("Der Lobpreis der Gnade",                         49,  1,  3,  1, 14),
        ("Die Waffenrüstung Gottes",                       49,  6, 10,  6, 20),
        ("Der Philipper-Hymnus",                           50,  2,  5,  2, 11),
        ("Alles vermag ich durch Christus",                50,  4, 10,  4, 20),
        ("Der Kolosser-Hymnus",                            51,  1, 15,  1, 20),
        ("Die Erscheinung der Güte",                       56,  3,  3,  3,  8),
        ("Der Hohepriester Jesus",                         58,  4, 14,  5, 10),
        ("Die Wolke der Zeugen",                           58, 11,  1, 12,  3),
        ("Der Glaube, der Taten fordert",                  59,  2, 14,  2, 26),
        ("Gott widersteht den Hoffärtigen",                59,  4,  1,  4, 10),
        ("Die Geduld Hiobs",                               59,  5,  7,  5, 11),
        ("Die neue Geburt",                                60,  1,  3,  1,  9),
        ("Die königliche Priesterschaft",                  60,  2,  4,  2, 10),
        ("Gott ist Licht",                                 62,  1,  5,  2,  2),
        ("Das Geheimnis der Gottseligkeit",                54,  3, 16,  3, 16),
        ("Die Berufung des Timotheus",                     44, 16,  1, 16,  5),
    ]),
    (18, "Die Offenbarung: Vollendung", "🌅", [
        ("Der Menschensohn",                        66,  1,  9,  1, 20),
        ("Die sieben Sendschreiben",                66,  2,  1,  3, 22),
        ("Der Thron Gottes und das Lamm",           66,  4,  1,  5, 14),
        ("Das neue Jerusalem",                      66, 21,  1, 22,  5),
        ("Der Ruf: Ja, ich komme bald",             66, 22,  6, 22, 21),
    ]),
]


def build_json() -> dict:
    themes_out = []
    passages_out = []
    pid = 1
    for theme_id, name, icon, passages in THEMES:
        themes_out.append({"id": theme_id, "name": name, "icon": icon})
        for sort_order, (title, book_id, cf, vf, ct, vt) in enumerate(passages, 1):
            passages_out.append({
                "id":           pid,
                "theme_id":     theme_id,
                "sort_order":   sort_order,
                "title":        title,
                "book_id":      book_id,
                "chapter_from": cf,
                "verse_from":   vf,
                "chapter_to":   ct,
                "verse_to":     vt,
            })
            pid += 1
    return {"themes": themes_out, "passages": passages_out}


if __name__ == "__main__":
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    data = build_json()
    with open(OUTPUT, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Written {len(data['themes'])} themes, {len(data['passages'])} passages → {OUTPUT}")
